### ISSUE TITLE
Member items in F2P are called "Member item"

### ISSUE THREAD

**Issue by JDennis95** [equirs/fashionscape-plugin#1]
I would love to mess around with Fashionscape in f2p.

But i can't look for member items because every member item does not have it's own name. 
Can this be fixed?

**Comment by equirs** [comment]
Hey, thanks for bringing this up. The names of all the items you see in this plugin come directly from the game client, and when you're in a f2p world, the client only knows their names as "Members object". So while it might be possible on my end to side-step that and map all of the members-only item ids to their actual names, I'm not sure if it's really worth going through and I'm also kind of hesitant to do it. My first thought when seeing this issue was that maybe I could hide all of the members-only items when in f2p, but that also seems unfair to people who are f2p and want to see what members items look like on them. I'll leave this issue open for now, I'm not sure what the resolution should be.

**Comment by JDennis95** [comment]
Is it possible to make an ID and item name list and have it pull the info from there? 

For now i'll just keep scrolling and looking at pictures. i'm good at that, might even find some new stuff!

**Comment by equirs** [comment]
> Is it possible to make an ID and item name list and have it pull the info from there?

It is possible, it's just a matter of whether I feel it's worth maintaining a massive lookup table of all the item names. While I could probably automatically populate it once, I would have to continually update it with each new item, and there are literally tens of thousands of items in the game. There's a lot of stuff under the hood that this plugin takes care of already (for example, I have to manually handle things like setting animations for weapons and deciding whether or not to show the player's hair for helmets; see [ItemInteractions](https://github.com/equirs/fashionscape-plugin/blob/master/src/main/java/eq/uirs/fashionscape/data/ItemInteractions.java)), so that's my main hesitation. That and just about every other plugin out there has this same "Members object" behavior.

One possible workaround for this: if you want to know what a p2p item name is, you can save the outfit and look at the text file for its item id, and then use something like [OSRSBox](https://www.osrsbox.com/tools/item-search/) to get the item's name. It's not ideal but it's better than having no idea what you're looking at.

**Comment by equirs** [comment]
Jagex has pretty much fixed this issue themselves now
