### ISSUE TITLE
Falconer's Glove

### ISSUE THREAD

**Issue by exp-lamp** [equirs/fashionscape-plugin#16]
the falconer's glove sometimes does have a flacon on it but the one with a falcon seems to be unsearchable.

The falconer's glove, since it's introduction it has been my favorite item in the game now i can finally use it as my companion in battle.
For now I get by using the bow and arrow cape slot item and the falconer's glove as my main weapon, while fighting with a bow.

I'm not sure if it's doable or worth your time.
    
 Ideally, what I want to do with your add on is to replace the arrows my bow shoots for the same particle that's fired when you use the falconer's glove when hunting.
I would also like to replace cast spells with my falcon boy attacking the faces of my enemies.
If it would be possible to change the the override and animations based on the weapons you are using that would be cool but i think you said it's not possible.
If this were something you could do though I'd love to swing a sword with the d hally spec animation and have that red particle shoot out at my enemies as an override for casting spells.

I think it would also be neat to be able to wield main hand items in the off hand, so i could use my falconer's glove which is already on my left hand, as an off hand item with a real weapon.
Dual 2h swords ect.

Just wanna say thanks for the plugin, it's made my experience in osrs much better.

**Comment by equirs** [comment]
> the falconer's glove sometimes does have a flacon on it but the one with a falcon seems to be unsearchable

Is it? I have no problem searching for the version with the falcon:
![fg](https://user-images.githubusercontent.com/77648102/114735904-7a260080-9cfa-11eb-826c-56e707fb23e6.png)

There are a few other suggestions here, most of which off the bat I feel is not really feasible or in scope for this plugin:

> Ideally, what I want to do with your add on is to replace the arrows my bow shoots for the same particle that's fired when you use the falconer's glove when hunting.
I would also like to replace cast spells with my falcon boy attacking the faces of my enemies.
If it would be possible to change the the override and animations based on the weapons you are using that would be cool but i think you said it's not possible

Not really something I'm interested in working on for fashionscape. The plugin currently changes your character's animations but it always changes them to the "real" idle animation. There's another plugin where you might want to make this suggestion, I think it should work alongside this one:
https://github.com/geheur/weapon-animation-replacer

> I think it would also be neat to be able to wield main hand items in the off hand, so i could use my falconer's glove which is already on my left hand, as an off hand item with a real weapon.
Dual 2h swords ect.

An interesting idea but not something that would work in practice. I've tried equipping items in the "wrong" slot before, so like in the example of equipping a main hand weapon in the shield slot, the weapon will still render in your main hand, so they'll just overlap each other and look broken. If there's a way to do this, it would be way more involved than simply changing item ids. Also, it doesn't really fit with the options the plugin currently provides. I try to keep it so that all the options you have are realistically doable in the game.
