### ISSUE TITLE
Feature Suggestion - Force body/legs/shoes models for opposite gender?

### ISSUE THREAD

**Issue by DBHHeroesJojy** [equirs/fashionscape-plugin#6]
There are a number of outfits (Elven clothes, Vyrewatch outfit, prince/princess outfit) which look entirely different depending on the characters gender. Would it be possible to get a toggle to enforce male/female variants of slots to allow for more fashionscape options? I know this doesn't quite fall under the "discovery and planning" goal of the plugin, since it's not something one could actually do ingame normally, but I figured it can't hurt to run it by you and see.

**Comment by equirs** [comment]
To be clear, you're not requesting to change your gender through the plugin, you just want the opposite gender's models on your character? 

There are two problems with this: one is that I don't know if there is a way to "trick" the method that the client uses when requesting a model for an item id, since that's directly tied with your player's gender (unless I provide a way to change gender entirely in the plugin, which I might support someday). The other thing is that the models are not going to look right on the opposite gender anyway since they are scaled for male/female models and sometimes include their own body models to go along with the item, so they won't really look like you're wearing the clothes for the other gender, instead your body parts will look disjointed and weird.

**Comment by cooperka** [comment]
Hi @equirs, in that case could we simply have the option to set gender through the plugin, or is that technically impossible for some reason? I'd be happy to help implement if necessary.

**Comment by equirs** [comment]
> Hi @equirs, in that case could we simply have the option to set gender through the plugin, or is that technically impossible for some reason? I'd be happy to help implement if necessary.

Unfortunately, this plugin (among other transmog plugins) is unable to do anything that isn't already part of the public RuneLite API, and there isn't any method for changing gender. It would require bothering Adam or another RL admin to add that capability in, and they're less willing to do that for hub plugins that heavily use functionality originally intended for development purposes only. I'm not in a rush to bug them about it, especially since I've been working around this myself by using the makeover mage or an alt.

**Comment by cooperka** [comment]
Thanks for the info, makes sense and I'll keep using the same workaround as you!
