### ISSUE TITLE
Missing items report

### ISSUE THREAD

**Issue by fuzxi** [equirs/fashionscape-plugin#62]
Currently the unfortified Elidinis' ward is missing, in addition to all of the new items from last week's Bounty Hunter update (besides the ones available in the beta - some of these had their models changed, such as Dragon claws).

**Comment by equirs** [comment]
Thanks for reporting, should get the ward into the plugin with the next update. BH items were missing because RuneLite hadn't yet run the wiki scraper, but they may or may not play well with the player's hair/beard/arms until I submit an update along with the missing ward (and probably some others, as I recall hiding them from the plugin while they were released in beta with placeholder models)

**Comment by equirs** [comment]
Should be fixed now if you restart the client
