### ISSUE TITLE
Items missing from search 

### ISSUE THREAD

**Issue by geheur** [equirs/fashionscape-plugin#8]
![image](https://user-images.githubusercontent.com/41499327/110837138-b971b500-8255-11eb-884d-249c633652c8.png)

Couldn't find these items: necklace of passage, games necklace, glory (charged), expeditious bracelet, bracelet of slaughter. Not an exhaustive list of course. I was logged in on a members world when searching.

**Comment by equirs** [comment]
I think some or all of these might be due to the de-dupe logic, which excludes items that share the same icon data (same base and same recolors). I probably want to fix that so that it de-dupes by model data, but I'm not sure if that affects anything. Jewelry tends to be duplicated often, though, so the passage is probably because the jade necklace exists, games necklace because the sapphire necklace exists, etc. That's intended behavior, but the icon vs model thing might be a problem.
